spring:
  application:
    name: demoCrud
  datasource:
    url: jdbc:postgresql://localhost:5432/db_crud
    username: postgres
    password: abc123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default-schema : public